20 сверстать общий лэйаут
openworld-community/ows-events-parsing-frontend pull request #31
Opened 2023-07-14 02:41 UTC by moonlightboss

1.Добавил простой хеддер, думаю лучше доделать когда выберем компонент либу, ознакомился с квазаром и с ним делать хеддер было бы проще, например.
![изображение](https://github.com/openworld-community/ows-events-parsing-frontend/assets/63856802/72bb0227-1d53-42ee-84b2-7b76723351f6)
2.Добавил просто пустой футер с затычками, не супер уверен что именно это от меня и требовалось

2023-07-21 09:02 UTC, HugeLetters requested changes

2023-07-21 09:02 UTC, HugeLetters commented on components/footer.vue
> +<style>
Стайл тегом в нашем случае следует пользоваться, только если нужен какой-то навороченный CSS (с использованием нескольких вложенных псевдо-селекторов, например), а так пользоваться функционалом тейлвинда все же. Хотя даже с псевдо-селекторами тейлвинд вполне в состоянии справиться.
\+ следует пользоваться scoped атрибутом, чтобы стайлинги не "утекали" в другие компоненты.

В данном случае все это можно переписать чисто с помощью ТВ

2023-07-21 09:02 UTC, HugeLetters commented on components/footer.vue
> +.bg-custom-blue {
Цвет фона я бы, наверное, вынес в `app.vue` - там в стайл теге вполне удобно хранить какой-то глобальный css. И там тогда можно на `body` весь накинуть этот фон с помощью [theme()](https://tailwindcss.com/docs/functions-and-directives#theme)

2023-07-21 09:02 UTC, HugeLetters commented on components/footer.vue
> +        <div class="container mx-auto text-center">
Надо подчистить неиспользуемые классы типу `container`

2023-07-21 09:02 UTC, HugeLetters commented on components/header.vue
> +const isClosed = ref(true);
На всякий случай лучше стартовое значение указать как `window.scrollY > 0` тоже.

2023-07-21 09:02 UTC, HugeLetters commented on components/header.vue
> +    window.addEventListener('scroll', () => {
Раз добавляешь `eventListener`, то также не забудь сделать его очистку при анмаунте

2023-07-21 09:02 UTC, HugeLetters commented on components/header.vue
> +    <header :class="{ 'header-open': !isClosed, 'header-closed': isClosed }">
Класс `'header-open'` не используется нигде.
Ну и опять же надо переписать на ТВ

2023-07-21 09:02 UTC, HugeLetters commented on components/header.vue
> +                src=""
Забыл указать сурс к лого

2023-07-21 09:02 UTC, HugeLetters commented on components/header.vue
> +        /
Я бы это лучше переписал как [for loop](https://vuejs.org/guide/essentials/list.html#v-for) - и тогда слэши бы сделал частью рендера внутри лупа, чтоб если вдруг мы добавили меню навигации, этот весь визуал автоматически бы подстроился

2023-07-21 09:02 UTC, HugeLetters commented on components/header.vue
> +        <div class="nav-link">Пункт меню</div>
Раз это пункт меню, то думаю, это явно `<a/>` или даже `<NuxtLink/>`

2023-07-21 09:02 UTC, HugeLetters commented on components/header.vue
> +        <div class="nav-link">Пункт меню</div>
Также я бы весь этот список пунктов меню навигации вынес в `<nav/>` для корректной семантики - так и стилизовать проще будет.
Потому что сейчас у нас 
```html
<LOGO/>
<MENU ITEM/>
<MENU ITEM/>
<MENU ITEM/>
<MENU ITEM/>
<LOGIN/>
```
а логичнее иметь структуру
```html
<LOGO/>
<MENU>
  <MENU ITEM/>
  <MENU ITEM/>
  <MENU ITEM/>
  <MENU ITEM/>
</MENU>
<LOGIN/>
```
Псевдо-код, но надеюсь, идею понятно передал

2023-07-21 09:02 UTC, HugeLetters commented on components/header.vue
> +    position: fixed;
Советую зайти на страницу профайла и посмотреть, что тут выглядит не так 👀
Как заметишь - напиши, я подскажу как исправить)

2023-07-21 09:02 UTC, HugeLetters commented on components/header.vue
> +    z-index: 9999;
Рекомендую также пройтись на CSS и почистить его от всяких лишних ничего не делающих свойств - с этим будет в будущем проще работать, чтобы не пришлось думать а нужно ли тут это вообще, если это вдруг начнет чему-то мешать.

```css
top: 0;
left: 0;
right: 0;
z-index: 9999;
```
Все это в данном случае, по-моему, излишне - что-то еще тоже вполне может быть.

2023-07-21 09:02 UTC, HugeLetters commented on components/header.vue
> +    font-size: 24px;
Никогда не надо ставить шрифт прямо в пикселях - это конфликтует с личными настройками юзера(некоторые люди плохо видят и ставят шрифт побольше). 
Нужен шрифт в полтора раза больше стандартного? Используй 1.5rem.

2023-07-21 09:02 UTC, HugeLetters commented on components/header.vue
> +header h1 {
Лишний код

2023-07-21 09:02 UTC, HugeLetters commented on components/header.vue
> +    background: var(--gradient-primary-vertical, linear-gradient(180deg, #48c78e 0%, #21a86b 100%));
Понятно, что это на Фигме так написано, но `var(--gradient-primary-vertical)` у нас нигде нет.

2023-07-21 09:02 UTC, HugeLetters commented on components/header.vue
> +    /* airbnb-box-shadow */
А?)

2023-07-21 09:02 UTC, HugeLetters commented on components/header.vue
> +    gap: 10px;
`gap` и `justify-content` лишние явно.

2023-07-21 09:02 UTC, HugeLetters commented on components/header.vue
> +    background: var(--primary-green, #48c78e);
Если хочешь, можешь подзапариться и запилить красивый транзишн по ховеру чтоб цвет из градиента в обычный переходил. Ну пока не обязательно это

2023-07-21 09:02 UTC, HugeLetters commented on components/logo.svg
Лого стоит перетащить в [assets](https://nuxt.com/docs/guide/directory-structure/assets), либо в [public](https://nuxt.com/docs/guide/directory-structure/public)

2023-08-08 19:36 UTC, HugeLetters requested changes

2023-08-08 19:36 UTC, HugeLetters commented on app.vue
> +    <div class="w-full bg-accent-navy-dark">
`w-full` лишний, блочные элементы и так занимают все ширину по возможности

2023-08-08 19:36 UTC, HugeLetters commented on app.vue
> +        <div class="sm:px-6 md:px-8 lg:px-10 xl:px-16">
Имеет смысл вешать паддинг не на страницу, хедер и футер отдельно, а просто на самый корневой div в `app.vue`

Также нет необходимости оборачивать страницу в див - все эти классы можно повестить на сам NuxtPage и классы замерджатся на корневой элемент страницы. 

Также я бы оставил просто один брейкпоинт и все - не вижу смысла городить их так. Достаточно добавить паддинг `lg:px-16` и все. Тем более, что у нас в принципе нет таргета на мобилки с этим сервисом.

2023-08-08 19:36 UTC, HugeLetters commented on components/Copyright.vue
Не надо настолько дотошно дробить все на компоненты - тут 3 строчки кода. Если вдруг в будущем этот элемент обрастет функционалом настолько, что станет целесообразно вынести в отдельный компонент - тогда и вынесем

2023-08-08 19:36 UTC, HugeLetters commented on components/Copyright.vue
> +    <div class="flex w-3/12 justify-end text-base text-input-text">@ Afisha Peredelano</div>
`text-base` - надо было повесить на самый корневой div в app.vue, чтобы не писать это потом повсюду. Это ж самый базовый шрифт 1rem. Шрифт 14 пикселей это дефолтная настройка от квазара. 

Здесь можно убрать все кроме `text-input-text`. Для позиционирования достаточно на родителя накинуть `justify-between`, чтобы элементы расположились друг от друга как можно дальше

2023-08-08 19:36 UTC, HugeLetters commented on components/FooterBottomNav.vue
> +    content: none;
А вот как раз сделать компонент для ссылок, в которым был бы прописан этот стайлинг явно бы не помешало.

2023-08-08 19:36 UTC, HugeLetters commented on components/FooterBottomNav.vue
Опять же, по-моему, излишняя абстракция с вытаскиванием в отдельный компонент.

2023-08-08 19:36 UTC, HugeLetters commented on components/FooterBottomNav.vue
> +    <ul class="flex w-9/12 items-center justify-end gap-10">
Тут ничего кроме флекса и гапа не нужно - лучше на родительском элементе расположение это все проставить.

2023-08-08 19:36 UTC, HugeLetters commented on components/FooterBottomNav.vue
> +.footer-link::after {
Ну и все это вполне в тейлвинде можно реализовать

2023-08-08 19:36 UTC, HugeLetters commented on components/FooterNavProject.vue
> +defineProps({
Желательно использовать все же тайпскриптовый синтакс
```ts
<script setup lang="ts">
defineProps<{
    title: string;
    projectLinks: { title: string; route: string }[];
}>();
</script>
```

2023-08-08 19:36 UTC, HugeLetters commented on components/FooterNavProject.vue
> +        <h3 class="mb-8 text-base text-white">{{ title }}</h3>
По макету цвет текста серенький + жирный.

К слову `text-base` можно будет позже убрать, если все же решим избавляться от Квазара.

2023-08-08 19:36 UTC, HugeLetters commented on components/FooterNavProject.vue
> +    <div class="">
По макету весь текст выровнен по правому краю

2023-08-08 19:36 UTC, HugeLetters commented on components/FooterNavProject.vue
> +                <NuxtLink
Как уже писал ранее это стоило вытащить в отдельный компонент

2023-08-08 19:36 UTC, HugeLetters commented on components/FooterNavProject.vue
> +                class="mb-4"
Проще просто `gap` повесить на родителя

2023-08-08 19:36 UTC, HugeLetters commented on components/FooterNavMenu.vue
По-моему, это то же самое, что и `FooterNavProject.vue` - почему бы этим и не воспользоваться?

2023-08-08 19:36 UTC, HugeLetters commented on components/FooterNav.vue
> +    <div class="footer__item flex w-full justify-end gap-60">
`footer__item` лишний. Плагин тейлвинда для преттиера сортирует тебе все классы и сначала идут классы, которые не распознаны тейлвиндом - так проще замечать такие вещи.

gap стоит подправить на 56.

2023-08-08 19:36 UTC, HugeLetters commented on components/FooterNav.vue
Излишний компонент, мне кажется, по итогу - проще все это прямо в футер и вставить. Тем более, тогда этот верхний див не нужен, так как все это прямо в футере задать можно.

2023-08-08 19:36 UTC, HugeLetters commented on components/footer.vue
Ну как же уже обсуждали вроде - файл стоит в PascalCase переименовать.

В целом, думаю, тут уместнее использовать grid, чтобы как по макету ряды соотносились друг с другом(инфа о проекте по той же вертикали, что и юр. информация, инфа о сообществе и копирайт тег тоже). Поделить на 4 колонки и распределить. между элементами

Также, наверное, есть смысл все компоненты, относящиеся только к футеру просто в отдельную папку в компонентах вынести для удобной структуры. И лучше, я думаю, Footer переименовать в FooterTemplate какой-нибудь, потому что я сталкивался с конфликтами в Наксте, когда кастомный компонент называется так же, как нативный элемент из HTML.

2023-08-08 19:36 UTC, HugeLetters commented on components/footer.vue
> +        class="lg:pt-15 bg-accent-navy-dark text-white sm:px-6 md:px-8 md:pb-8 md:pt-10 lg:px-10 lg:pb-10 xl:px-16 xl:pb-12 xl:pt-20"
`pt-15` - такого класса нет в ТВ 👀
Вот я как раз и писал про сортировку классов преттиеров поэтому - очень легко заметить если где-то опечатался вдруг.

Ну и как я писал ранее - не нужно столько брейкпоинтов и проще эти паддинги просто на самый корневой элемент в приложении повесить

Цвет фона и текста опять же в корневом могут быть просто заданы

2023-08-08 19:36 UTC, HugeLetters commented on components/logo.svg
Этот файл нигде не используется

2023-08-08 19:36 UTC, HugeLetters commented on app.vue
В макете используется шрифт Inter - надо добавить его загрузку из гугл шрифтов. Робото мы не используем. 
И также настроить тейлвинд, чтоб он использовал этот шрифт по умолчанию.
И также удостовериться, что Квазар не перезаписывает эту настройку.

2023-08-08 19:36 UTC, HugeLetters commented on assets/img/afisha-api-logo.svg
Надо выгрузить с фигмы корректный ассет - тут лишнее пространство справа, из-за которого сложно выставлять размер логотипа

2023-08-08 19:36 UTC, HugeLetters commented on components/footer.vue
> +                    <Logo />
Лучше указать прямо размер логотипа, чтоб в будущем ничего не поплыло

2023-08-08 19:36 UTC, HugeLetters commented on components/icon/Github.vue
Это лишнее, если есть уже ассет такой

2023-08-08 19:36 UTC, HugeLetters commented on components/icon/Instagram.vue
Это лишнее, если есть уже ассет такой

2023-08-08 19:36 UTC, HugeLetters commented on components/icon/Linkedin.vue
Это лишнее, если есть уже ассет такой

2023-08-08 19:36 UTC, HugeLetters commented on components/icon/Telegram.vue
Это лишнее, если есть уже ассет такой

2023-08-08 19:36 UTC, HugeLetters commented on components/icon/Twitter.vue
Это лишнее, если есть уже ассет такой

2023-08-08 19:36 UTC, HugeLetters commented on assets/img/icons/telegram-icon.svg
Ассеты можно выгружать напрямую с фигмы.
![image](https://github.com/openworld-community/ows-events-parsing-frontend/assets/119697239/48e7bd48-190e-48d2-aa6c-a0dfa66b5693)

2023-08-08 19:36 UTC, HugeLetters commented on components/SocialIcons.vue
Не вижу смысла выносить в отдельный компонент - также когда добавим ПР от Милы с настройкой анплагин-айконс, то надо будет поменять как иконки выгружаются. 

А так это все логичнее через `v-for` сделать просто

2023-08-08 19:36 UTC, HugeLetters commented on components/SocialIcons.vue
> +            <IconInstagram class="icon w-7 hover:fill-accent-blue-main" />
По макету иконки 32 пикселя, а не 28.
Класс `icon` лишний

С ховером тогда можно пока повременить, пока неясно как иконки у нас будут грузиться - позже что-нибудь придумаем. Пока что пусть белые будут просто

2023-08-08 19:36 UTC, HugeLetters commented on components/SocialIcons.vue
> +    <div class="flex max-w-[256px] items-center justify-between gap-6">
Достаточно `flex gap-6`

2023-08-08 19:36 UTC, HugeLetters commented on components/HeaderSignIn.vue
> +<style scoped>
Вынести в отдельный компонент как уже писал ранее.

2023-08-08 19:36 UTC, HugeLetters commented on components/HeaderSignIn.vue
> +            class="btn-register rounded-3xl bg-accent-green-dark px-6 py-2 text-base text-white hover:bg-accent-green-main"
`py-3` должен быть по макету
`btn-register text-base text-white` - можно убрать 
Цвет у кнопки градиентом - можешь поставить плагин [тейлвинда для фигмы](https://www.figma.com/community/plugin/842128343887142055), там многие вещи сразу в коде для тейлвинда будут показываться. не надо конечно оттуда слепо копировать, но упрощает работу
Также у кнопки легкая тень

2023-08-08 19:36 UTC, HugeLetters commented on components/HeaderSignIn.vue
> +        <span class="text-base text-white">/</span>
Классы лишние

2023-08-08 19:36 UTC, HugeLetters commented on components/HeaderSignIn.vue
> +    <div class="header-btn ml-auto flex items-center gap-4">
`header-btn ml-auto` - я бы убрал, тк стайлинг этих классов определяется в родительском компоненте, из-за чего сложно отслеживать что откуда идет.

2023-08-08 19:36 UTC, HugeLetters commented on components/Navbar.vue
> +<script setup lang="ts">
Лучше скрипт ставить в начало файла - это сугубо мое личное предпочтение, да. Но, по-моему, оно наиболее логичное, потому что сначала идут переменные, определенные в скрипте, а после ты их используешь в темплейте + часто приходится скакать между темплейтом и стайлом или темплейтом и скриптом, а вот скакать между скрипто и стайлом приходится редко, потому уместнее держать их рядом в таком порядке

2023-08-08 19:36 UTC, HugeLetters commented on components/Navbar.vue
Тоже лишний компонент, я считаю - пусть это прямо в хедере и будет.

2023-08-08 19:36 UTC, HugeLetters commented on components/Navbar.vue
> +.header-closed .nav .link::before {
`.header-closed` опять же контролировать css через классы из каких-то других компонентов - не очень идея, потому что в будущем тяжело отслеживать что откуда идет

2023-08-08 19:36 UTC, HugeLetters commented on components/Navbar.vue
> +        <NuxtLink
Лучше обернуть в `<li>` и тогда слэш можно на ::after у него повесить, а подчеркивание уже на самой ссылке - и тогда не придется ниже делать эти манипуляции над шириной

2023-08-08 19:36 UTC, HugeLetters commented on components/Navbar.vue
> +    <ul class="mt-8 flex w-full items-center justify-center gap-8">
Достаточно оставить `flex justify-center gap-6`, а марджин заменить на gap уже в родителей

2023-08-08 19:36 UTC, HugeLetters commented on components/Navbar.vue
> +.link::before {
`.link:not(:last-child)::after` - можно так просто
Все кроме контента лишнее в целом.

Можно добавить марджина, чтобы компенсировать gap между ссылками в раскрытом состоянии

2023-08-08 19:36 UTC, HugeLetters commented on components/header.vue
С неймингом аналогично футеру.

Мне кажется не очень удачной идеей делать смену лейаута через позишн абсолют - особенно с интерактивными элементами, это может плачевно сказываться на доступности. 
Я по итогу какой-то такой лейаут запилил - как-то в будущем надо придумать как бы это еще анимировать все.
```html
<template>
    <header
        class="sticky top-12 grid items-center gap-8"
        :class="[isClosed ? 'header-closed' : 'grid-flow-dense grid-cols-4']"
    >
        <NuxtLink
            to="/"
            class="justify-self-center"
            :class="[{ 'col-span-2 col-start-2': !isClosed }]"
        >
            <Logo class="h-9" />
        </NuxtLink>
        <ul
            class="flex gap-6"
            :class="[isClosed ? 'col-span-3' : 'nav-open col-span-4 justify-center']"
        >
            <li
                v-for="link in links"
                :key="link.title"
                class="navlink"
            >
                <PrettyLink :to="link.route">
                    {{ link.title }}
                </PrettyLink>
            </li>
        </ul>
        <HeaderSignIn
            class="justify-self-end"
            :class="[{ 'col-start-4': !isClosed }]"
        />
    </header>
</template>

<style scoped>
.nav-open .navlink:not(:last-child)::after {
    content: '/';
    margin-left: theme('margin.8');
    margin-right: theme('margin.2');
}
.header-closed {
    grid-template-columns: auto repeat(4, 1fr);
}
</style>

```

2023-08-08 19:36 UTC, HugeLetters commented on components/header.vue
> +        class="header bg-accent-navy-dark sm:px-6 sm:py-6 md:px-8 md:py-6 lg:px-10 lg:py-8 xl:px-16 xl:py-10"
Все кроме цвета фона и падднга можно убрать, я думаю. И не нужно столько брейкпоинтов

2023-08-08 19:36 UTC, HugeLetters commented on components/header.vue
> +    transition: all 0.3s ease;
Используй `transition: all` по минимуму потому что он жрет перформанс - как правило ты и так прекрасно заранее знаешь, какие проперти тебе нужно анимировать

2023-08-08 19:36 UTC, HugeLetters commented on components/header.vue
> +    isClosed.value = window.scrollY > 0;
Надо на будущее оставить заметку, что есть проблема, когда страница высоты чуть-чуть побольше чем высота экрана. Потому что как только ты скроллишь, хедер становится меньше, вся страница становится меньше, страница становится высотой меньше чем экран, триггерится скролл=0, из-за чего хедер снова раскрывается и так по кругу.

2023-08-09 10:07 UTC, HugeLetters commented on app.vue
> +    <div class="w-full bg-accent-navy-dark">
Я подумал насчет паддингов - лучше так сделать, в общем, наверное, как-то
```html
        <HeaderTemplate class="p-2 lg:px-12 lg:py-10" />
        <NuxtPage class="px-2 lg:px-12" />
        <FooterTemplate class="p-2 lg:px-12 lg:pb-10" />
```

2023-08-10 22:15 UTC, HugeLetters requested changes

2023-08-10 22:15 UTC, HugeLetters commented on app.vue
> +            href: 'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;700&family=Raleway:wght@400;500;600;700&display=swap',
Мы разве где-то используем Raleway?

2023-08-10 22:15 UTC, HugeLetters commented on app.vue
> +            class="bg-accent-navy-dark p-2 before:absolute before:bottom-0 before:h-[2px] before:w-full before:bg-gradient-to-r before:from-accent-green-main before:to-accent-blue-main lg:px-12 lg:py
`h-[2px]` можно заменить на `h-0.5` - лучше предпочитать встроенные классы, а не кастомные значения по возможности, тк итоговый CSS весить будет меньше

2023-08-10 22:15 UTC, HugeLetters commented on assets/img/afisha-api-logo.svg
Я исправил уже, но если что из-за некорректного разрешения мердж конфликта файл сломался - у тебя там объединились оба варианта СВГ: твой локальный и тот что ты запулил с ремоута.

2023-08-10 22:15 UTC, HugeLetters commented on components/AppLink.vue
> +        class="footer-link relative after:absolute after:bottom-[-4px] after:left-0 after:h-1 after:w-full after:rounded-3xl after:bg-gradient-to-r after:from-accent-green-main after:to-accent-blue-m
`footer-link` - неиспользуемый класс.
`bottom-[-4px]` на `-bottom-1`
лучше `rounded-full` - будет работать с элементами любого размера

Вместо `after:w-full after:content-none hover:after:content-['']` можно же просто `hover:after:w-full`. В идеале бы еще какой-нибудь транзишн 
опасити или ширины плавный добавить :)

2023-08-10 22:15 UTC, HugeLetters commented on components/FooterTemplate.vue
> +    <footer class="lg:pt-16 xl:pt-20">
Паддинг указан и тут, и в `app.vue` - путанно как-то выходит. Плюс конкретно эти паддинги конкретно лишние, по-моему.

2023-08-10 22:15 UTC, HugeLetters commented on components/FooterTemplate.vue
> +            <Logo class="w-[150px]" />
`w-36` 👀

2023-08-10 22:15 UTC, HugeLetters commented on components/FooterTemplate.vue
> +        <div class="grid grid-cols-4 items-center justify-between">
`justify-between` лишний

2023-08-10 22:15 UTC, HugeLetters commented on components/FooterTemplate.vue
> +            <div class="flex flex-col items-end text-right">
`items-end` лишний

2023-08-10 22:15 UTC, HugeLetters commented on components/FooterTemplate.vue
> +                        class="mb-4"
В других местах используешь `gap`, а тут `mb` - лучше определиться на чем-то одном

2023-08-10 22:15 UTC, HugeLetters commented on components/FooterTemplate.vue
> +                        class="mb-4"
См. ниже

2023-08-10 22:15 UTC, HugeLetters commented on components/FooterTemplate.vue
> +        <div class="flex items-center justify-between pt-8">
Обрати внимание как в макете по обоим краям ровно сходятся элементы.
![image](https://github.com/openworld-community/ows-events-parsing-frontend/assets/119697239/db89e4b0-ace4-4469-8af6-342cfbc91c24)
Переписав этот весь блок через `grid` можно такого добиться, учитывая, что блок выше у тебя уже через грид

2023-08-10 22:15 UTC, HugeLetters commented on components/HeaderSignIn.vue
> +            class="rounded-3xl bg-gradient-to-r from-accent-green-dark to-accent-green-main px-6 py-3 shadow-md hover:bg-accent-green-light"
Лучше `rounded-full` раз нас интересуют полностью скругленные углы.
Градиент не в ту сторону
Ховер не работает и это не тот цвет.

2023-08-10 22:15 UTC, HugeLetters commented on components/HeaderSignIn.vue
Группируй компоненты по папкам

2023-08-10 22:15 UTC, HugeLetters commented on components/HeaderSignIn.vue
> +        <AppLink
Если сможешь, разберись, пожалуйста, почему у этой ссылки подчеркивание ниже, чем у других.

2023-08-10 22:15 UTC, HugeLetters commented on components/HeaderTemplate.vue
> +const isClosed = ref(true);
При загрузки страницы хедер сразу в закрытом состоянии

2023-08-10 22:15 UTC, HugeLetters commented on public/icons/github-icon.svg
В паблике хранятся ассеты, которые никак не надо трансформировать бандлеру - в плане, они будут оставлены в том виде, в каком есть. В ассетс же идут ассеты, которые надо трансформировать - то есть к ним будут применены всякие оптимизации. Так что уместнее всякие иконки хранить там. 
В данном случае забей, тк с анплагином позже интегрируем, но на будущее учти

2023-08-10 22:15 UTC, HugeLetters commented on tailwind.config.js
> +            addVariant('focused', ['&:hover', '&:focus-within']);
А я как раз этот вариант добавил, чтоб можно было фокусировку табом и ховер объединить в один селектор, так что вообще можно пользоваться так-то.

2023-08-11 08:00 UTC, HugeLetters requested changes

2023-08-11 08:00 UTC, HugeLetters commented on components/AppLink.vue
> +        {{ title }}
Можно воспользоваться слотами, чтоб сюда можно было вставлять не только текст
https://vuejs.org/guide/components/slots.html

2023-08-11 08:05 UTC, HugeLetters commented on components/AppLink.vue
> +    route: string;
Лучше назвать `to` - как и пропс на самом NuxtLink, чтобы у компонентов был одинаковый интерфейс. Удобно на будущее, когда, возможно, потребуется добавить и другие пропсы, которые есть у NuxtLink.
А вообще есть тип `NuxtLinkProps` - думаю, можно им тут как-то воспользоваться 👀

2023-08-11 18:56 UTC, HugeLetters requested changes

2023-08-11 18:56 UTC, HugeLetters commented on components/AppLink.vue
> +        class="link relative block after:absolute after:bottom-0 after:left-0 after:h-1 after:w-full after:rounded-full after:bg-gradient-to-r after:from-accent-green-main after:to-accent-blue-main a
Зачем `link` и `block`?

2023-08-11 18:56 UTC, HugeLetters commented on components/AppLink.vue
> +            {{ title }}
Внутри слота указывается значение по умолчанию на случай, если при пользовании элементом слот не был предоставлен. Почитай еще раз документацию, пожалуйста, которую я кидал.

2023-08-11 18:56 UTC, HugeLetters commented on components/AppLink.vue
> +    title: string;
Это не нужно, если есть слот.

2023-08-11 18:56 UTC, HugeLetters commented on components/FooterTemplate.vue
> +        <div class="grid grid-cols-[3fr,1fr] items-center pt-8">
Не сходится же, но ты близок к решению - я же говорил, что ты в моей ветке можешь подсмотреть решение, если прям уж не удается придумать что-то. 
![image](https://github.com/openworld-community/ows-events-parsing-frontend/assets/119697239/93ee1f8c-ee20-42e3-8d26-40ddf3eb34ae)

2023-08-11 18:56 UTC, HugeLetters commented on components/FooterTemplate.vue
> +            <ul class="flex items-center justify-end gap-14">
А сюда `col-span-2 col-start-2 justify-between`. И все. gap не нужен

2023-08-11 18:56 UTC, HugeLetters commented on components/FooterTemplate.vue
> +                        :title="link.title"
У тебя же слот есть - зачем тайтл использовать?

2023-08-11 18:56 UTC, HugeLetters commented on components/FooterTemplate.vue
> +        <div class="grid grid-cols-[3fr,1fr] items-center pt-8">
Сюда `grid-cols-4`.

2023-08-11 18:56 UTC, HugeLetters commented on package.json
> -        "unplugin-icons": "^0.16.5"
Куда `unplugin-icons` делись?

2023-08-11 18:56 UTC, HugeLetters commented on components/header/HeaderSignIn.vue
> +            class="btn-login rounded-full bg-gradient-to-l from-accent-green-dark to-accent-green-main px-6 py-3 shadow-md"
Градиент все еще не в ту сторону

2023-08-11 18:56 UTC, HugeLetters commented on components/header/HeaderSignIn.vue
> +.btn-login:hover {
Так тоже можно решить проблему с ховером, но вообще разгадка была в том, что `bg-accent-green-main` меняет `background-color`, а градиент меняет `background-image`, который имеет приоритет над цветов. Так-то можно было просто на ховер менять `to-accent-green-dark` на `to-accent-green-main`

2023-08-11 18:57 UTC, HugeLetters commented on components/HeaderSignIn.vue
Если группируешь по папками, то внутри папки можно уж не дублировать название

2023-08-11 18:59 UTC, HugeLetters commented on components/header/HeaderSignIn.vue
> +    background: #48c78e;
Есть `theme('colors.accent.green.main')`, чтобы не копировать цвета, а пользоваться тем, что у нас определено в тейлвинде

2023-08-11 19:03 UTC, HugeLetters commented on components/header/HeaderTemplate.vue
> +            :class="[isClosed ? 'col-span-3' : 'nav-open col-span-4 justify-center']"
В открытом состоянии навбар некорректно выглядит - слэши стоят косо
![image](https://github.com/openworld-community/ows-events-parsing-frontend/assets/119697239/a660b425-891a-4965-9e78-3fb654721fc5)

2023-08-12 13:46 UTC, HugeLetters commented on components/AppLink.vue
> +        class="relative after:absolute after:bottom-[-4px] after:left-0 after:h-1 after:w-full after:rounded-full after:bg-gradient-to-r after:from-accent-green-main after:to-accent-blue-main after:c
Ссылка никуда не ведет

2023-08-12 15:13 UTC, HugeLetters approved these changes

2023-08-12 19:46 UTC, dvvinfo approved these changes

2023-08-12 19:46 UTC, merged